import { Hahmlet } from 'next/font/google'; // 앞에 숫자면 언더바(_)를 추가하고 2개 단어는 사이에 언더버(_) 추가
import './globals.css';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';

const hahmlet = Hahmlet({
    variable: '--font-hahmlet', // 가변(variable) 폰트일 경우 선언 (100-900 굵기 지원)
    subsets: ['latin'],
    // weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 가변 폰트는 굵기 설정 필요 없음
    // font-thin, extraLight, light, regular, medium, semiBold, bold, extraBold, black
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${hahmlet.variable} antialiased`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
